# Gatus configuration for AbuCloud1 Monitoring Dashboard
# The application will run on port 8080 by default

# Customize the dashboard appearance
ui:
  title: "Abubakkers Status Dashboard"
  header: "Abubakkers Real-time ECS Observability and Health Monitoring"
  accent-color: "#3B82F6"  # Blue accent color
  primary-color: "#1F2937"  # Dark gray primary
  secondary-color: "#6B7280"  # Medium gray secondary

defaults: &check_defaults
  interval: 60s
  conditions:
    - "[STATUS] == 200"

endpoints:
  # Social Media & Communication
  - name: "Instagram"
    url: "https://www.instagram.com"
    description: "Social media platform for sharing photos and videos"
    group: "Social Media"
    <<: *check_defaults

  - name: "Twitter"
    url: "https://www.twitter.com"
    description: "Microblogging and social networking service"
    group: "Social Media"
    <<: *check_defaults

  - name: "Facebook"
    url: "https://www.facebook.com"
    description: "Social networking platform connecting people worldwide"
    group: "Social Media"
    <<: *check_defaults

  - name: "LinkedIn"
    url: "https://www.linkedin.com"
    description: "Professional networking and career development platform"
    group: "Professional"
    <<: *check_defaults

  # Entertainment & Streaming
  - name: "YouTube"
    url: "https://www.youtube.com"
    description: "Video sharing and streaming platform"
    group: "Entertainment"
    <<: *check_defaults

  - name: "Netflix"
    url: "https://www.netflix.com"
    description: "Streaming service for movies and TV shows"
    group: "Entertainment"
    <<: *check_defaults

  - name: "Twitch"
    url: "https://www.twitch.tv"
    description: "Live streaming platform for gamers and creators"
    group: "Entertainment"
    <<: *check_defaults

  - name: "Spotify"
    url: "https://open.spotify.com"
    description: "Music streaming and podcast platform"
    group: "Entertainment"
    <<: *check_defaults

  # Technology & Development
  - name: "GitHub"
    url: "https://www.github.com"
    description: "Code hosting and version control platform"
    group: "Development"
    <<: *check_defaults

  - name: "Stack Overflow"
    url: "https://stackoverflow.com"
    description: "Q&A platform for programmers and developers"
    group: "Development"
    <<: *check_defaults

  - name: "Medium"
    url: "https://medium.com"
    description: "Publishing platform for writers and creators"
    group: "Content"
    <<: *check_defaults

  # Productivity & Business
  - name: "Notion"
    url: "https://www.notion.so"
    description: "All-in-one workspace for notes and collaboration"
    group: "Productivity"
    <<: *check_defaults

  - name: "Slack"
    url: "https://slack.com"
    description: "Team communication and collaboration platform"
    group: "Business"
    <<: *check_defaults

  - name: "Zoom"
    url: "https://zoom.us"
    description: "Video conferencing and online meeting platform"
    group: "Business"
    <<: *check_defaults

  # E-commerce & Services
  - name: "Amazon"
    url: "https://www.amazon.com"
    description: "Online marketplace and e-commerce platform"
    group: "E-commerce"
    <<: *check_defaults

  - name: "Microsoft"
    url: "https://www.microsoft.com"
    description: "Technology company and software provider"
    group: "Technology"
    <<: *check_defaults

  - name: "Apple"
    url: "https://www.apple.com"
    description: "Consumer electronics and software company"
    group: "Technology"
    <<: *check_defaults

  - name: "Dropbox"
    url: "https://www.dropbox.com"
    description: "Cloud storage and file sharing service"
    group: "Storage"
    <<: *check_defaults