name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pre-commit
      run: pip install pre-commit
        
    - name: Run pre-commit
      run: pre-commit run --all-files
      
    - name: Terraform Init (Dev)
      run: |
        cd terraform/environments/dev
        terraform init -backend=false
        
    - name: Terraform Validate (Dev)
      run: |
        cd terraform/environments/dev
        terraform validate
        
    - name: Terraform Format Check (Dev)
      run: |
        cd terraform/environments/dev
        terraform fmt -check -recursive
