name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'garus-app/**'
      - '.github/workflows/build-gatus.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'garus-app/**'
      - '.github/workflows/build-gatus.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Install Checkov
      run: pip install checkov
        
    - name: Run Checkov Security Scan
      run: checkov --framework terraform --directory terraform/ --soft-fail --quiet || echo "Checkov completed with warnings"
        
    - name: Validate Dev Environment
      run: |
        cd terraform/environments/dev
        terraform init -backend=false
        terraform validate
        
    - name: Validate Staging Environment
      run: |
        cd terraform/environments/staging
        terraform init -backend=false
        terraform validate
        
    - name: Validate Prod Environment
      run: |
        cd terraform/environments/prod
        terraform init -backend=false
        terraform validate
